### PR TITLE
Ability to change Color of Title

### PR DESCRIPTION
**Pull request by ghost**
This PR allows you to set a custom color for the title

### CODE REVIEW

**Comment by ghost** [comment]
@AntoineFr Does it look OK?

**Comment by AntoineFr** [comment]
Hi ! Thanks for your pull request.

I think it adds more complexity to the extension settings, and it's not really needed by everyone.
When an admin wants to activate this extension, he would have to fill this field even if the default color (black) is enough for him.

If you want to change a color, you can do it in the Custom Styles area from the Appearance admin page.
I added a simple rule like the following one and it worked very well : 

```css
.OnlineUsers legend {
  color: red;
}
```

I'm sorry but I won't accept your pull request because I think it only concerns a small number of people.

**Comment by ghost** [comment]
No, I totally agree with what you say. I can understand where your coming from. Are there any other features that people want added that you haven't added yet @AntoineFr

**Comment by AntoineFr** [comment]
For now, the main problem is that this extension isn't showing all online users but only those whose profile has been shown during the session.

Here are the ideas that were expressed in the discussion on [Flarum's website](https://discuss.flarum.org/d/8302-online-users-extension) : 
- Hide some groups (https://discuss.flarum.org/d/8302-online-users-extension/8)
- Only display avatars and show the username on hover (https://discuss.flarum.org/d/8302-online-users-extension/28)

**Pull request closed without merging**
